main:
  params: [input]
  steps:
    - init:
        assign:
          - project_id: ${project_id}
          - region: ${region}
          - job_name: ${job_name}
          - max_retries: 3
          - retry_count: 0

    - log_start:
        call: sys.log
        args:
          text: $${{"Starting batch workflow for job " + job_name}}
          severity: INFO

    - execute_job_with_retry:
        try:
          steps:
            - run_job:
                call: googleapis.run.v2.projects.locations.jobs.run
                args:
                  name: $${"projects/" + project_id + "/locations/" + region + "/jobs/" + job_name}
                result: job_execution

            - log_job_started:
                call: sys.log
                args:
                  text: $${{"Job execution started: " + job_execution.name}}
                  severity: INFO

            - wait_for_completion:
                call: poll_job_execution
                args:
                  execution_name: $${job_execution.name}
                result: final_status

            - check_success:
                switch:
                  - condition: $${final_status.status.state == "SUCCEEDED"}
                    next: log_success
                  - condition: true
                    raise: $${{"Job execution failed with status: " + final_status.status.state}}

        retry:
          predicate: $${custom_retry_predicate}
          max_retries: $${max_retries}
          backoff:
            initial_delay: 2
            max_delay: 60
            multiplier: 2

        except:
          as: e
          steps:
            - log_error:
                call: sys.log
                args:
                  text: $${{"Workflow failed after retries: " + e.message}}
                  severity: ERROR

            - return_error:
                return:
                  success: false
                  error: $${e.message}
                  retry_count: $${retry_count}

    - log_success:
        call: sys.log
        args:
          text: "Batch workflow completed successfully"
          severity: INFO

    - return_success:
        return:
          success: true
          execution: $${job_execution.name}
          status: $${final_status.status.state}

# Subworkflow to poll job execution status
poll_job_execution:
  params: [execution_name]
  steps:
    - init_poll:
        assign:
          - max_poll_attempts: 60
          - poll_interval: 10
          - poll_count: 0

    - poll_loop:
        steps:
          - get_execution:
              call: googleapis.run.v2.projects.locations.jobs.executions.get
              args:
                name: $${execution_name}
              result: execution_status

          - log_status:
              call: sys.log
              args:
                text: $${{"Job status: " + execution_status.status.state}}
                severity: INFO

          - check_completion:
              switch:
                - condition: $${execution_status.status.state == "SUCCEEDED"}
                  return: $${execution_status}
                - condition: $${execution_status.status.state == "FAILED"}
                  return: $${execution_status}
                - condition: $${execution_status.status.state == "CANCELLED"}
                  return: $${execution_status}

          - increment_counter:
              assign:
                - poll_count: $${poll_count + 1}

          - check_timeout:
              switch:
                - condition: $${poll_count >= max_poll_attempts}
                  raise: "Job execution timeout: exceeded maximum polling attempts"

          - wait:
              call: sys.sleep
              args:
                seconds: $${poll_interval}

          - continue_polling:
              next: poll_loop

# Custom retry predicate
custom_retry_predicate:
  params: [e]
  steps:
    - check_retry:
        switch:
          - condition: $${e.code == 429}  # Too Many Requests
            return: true
          - condition: $${e.code == 503}  # Service Unavailable
            return: true
          - condition: $${e.code == 500}  # Internal Server Error
            return: true
          - condition: true
            return: false
